name: CD_android

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  android_build:
    name: Build and upload android app draft for internal test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
          channel: 'stable'
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies and generate files
        run: make gen
      - name: Prepare appbundle
        run: flutter build appbundle --release
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: beta
          subdirectory: android
      - name: Upload android build artifact
        uses: actions/upload-artifact@v3
        with:
          name: android_appbundle
          path: build/app/outputs/bundle/release/app-release.aab
