name: nightly_sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'

      - name: Get release version
          run: |
            git pull
            version=$(awk '/version:/ {match($0, /version:/); print substr($0, RSTART+9, RLENGTH + 12);}' pubspec.yaml)

      - uses: actions/checkout@v3
        with:
          ref: 'nightly'

      - name: checkout and rebase
        run: |
          git pull
          git merge origin/dev -m "n$version-$(date +%y%m%d)"
          git commit --amend -m "n$version-$(date +%y%m%d)"

      - name: Tag and Push Nightly Release
        run: |
          git tag n$version-$(date +%y%m%d)
          git push --atomic origin nightly n$version-$(date +%y%m%d)

