name: Nightly Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'nightly'

      - name: checkout, merge, tag and push
        run: |
          git pull
          git config --global user.email "${{ secrets.email }}"
          git config --global user.name "${{ secrets.username }}"
          git merge origin/dev -m "placeholder" --allow-unrelated-histories
          version=$(awk '/version:/ {match($0, /version:/); print substr($0, RSTART+9, RLENGTH + 12);}' pubspec.yaml)
          nversion="n$version-$(date +%y%m%d)"
          echo $nversion
          echo "$nversion"
          git commit --amend -m "$nversion"
          git tag $nversion
          git push --atomic origin nightly $nversion

