name: nightly_sync

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge dev -> nightly
        uses: devmasx/merge-branch@1.4.0
        with: 
          type: now
          from_branch: dev
          target_branch: nightly
          github_token: ${{ github.token }}

      - name: checkout and rebase
        run: |
          git checkout nightly
          git pull
          git rebase main

      - name: Tag and Push Nightly Release
        run: |
          version=$(awk '/version:/ {match($0, /version:/); print substr($0, RSTART+9, RLENGTH + 12);}' pubspec.yaml)
          git tag n$version-$(date +%y%m%d)
          git push --atomic origin nightly n$version-$(date +%y%m%d)

