name: nightly_sync

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge dev -> nightly
        uses: devmasx/merge-branch@1.4.0
        with: 
          type: now
          from_branch: dev
          target_branch: nightly
          github_token: ${{ github.token }}
          
      - name: grab app version
        run: version=$(awk '/version:/ {match($0, /version:/); print substr($0, RSTART+9, RLENGTH + 12);}' pubspec.yaml)

      - name: Tag Nightly Release
        run: git tag n$version-$(date +%y%m%d) nightly

      - name: Push tag
        run: git push origin n$version-$(date +%y%m%d)

