name: nightly_sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'

      - name: Get release version
        run: |
          git pull
          version=$(awk '/version:/ {match($0, /version:/); print substr($0, RSTART+9, RLENGTH + 12);}' pubspec.yaml)
          nversion="n$version-$(date +%y%m%d)"

      - uses: actions/checkout@v3
        with:
          ref: 'nightly'

      - name: checkout and rebase
        run: |
          git pull
          git merge origin/dev -m "$nversion"
          git commit --amend -m "$nversion"

      - name: Tag and Push Nightly Release
        run: |
          git tag $nversion
          git push --atomic origin nightly $nversion

