name: nightly_sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'nightly'

      - name: checkout and rebase
        run: |
          git pull
          git rebase dev

      - name: Tag and Push Nightly Release
        run: |
          version=$(awk '/version:/ {match($0, /version:/); print substr($0, RSTART+9, RLENGTH + 12);}' pubspec.yaml)
          git tag n$version-$(date +%y%m%d)
          git push --atomic origin nightly n$version-$(date +%y%m%d)

