name: Flutter Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
            java-version: '12.x'
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
